#!/bin/bash

# Küsi kasutajalt ridade ja veergude arv
read -p "Sisesta ridade arv: " ridu
read -p "Sisesta tärnide arv reas: " veerge

# Välimine tsükkel, mis liigub ridade järgi
for ((i=1; i<=ridu; i++)); do
    # Sisemine tsükkel, mis liigub veergude järgi
    for ((j=1; j<=veerge; j++)); do
        # Väljasta tärn ilma reavaheta
        echo -n "* "
    done
    # Liigu järgmisele reale
    echo
done
