#!/bin/bash

# Küsi kasutajalt ridade arv
read -p "Sisesta ridade arv: " ridu

# Välimine tsükkel, mis liigub ridade järgi
for ((i=1; i<=ridu; i++)); do
    # Sisemine tsükkel, mis liigub tärnide arvu järgi
    for ((j=1; j<=i; j++)); do
        # Väljasta tärn ilma reavaheta
        echo -n "* "
    done
    # Liigu järgmisele reale
    echo
done
