#!/bin/bash

# Luuakse muutuja aasta ning antakse sellele väärtuseks 2016
aasta=2016

# Luuakse muutuja president ning antakse sellele väärtuseks "Kersti Kaljulaid"
president="Kersti Kaljulaid"

# Luuakse muutuja lause_keskosa ning antakse sellele väärtuseks " aastal valiti Eesti presidendiks "
lause_keskosa=" aastal valiti Eesti presidendiks "

# Luuakse muutuja lause, mille väärtuse saamiseks ühendatakse muutujad aasta, lause_keskosa ja president
lause="$aasta$lause_keskosa$president"

# Väljastatakse muutuja lause väärtus ekraanile
echo $lause

